### ISSUE TITLE
Add a new operator type of 'null'

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_api#104]
There's a limitation at the moment with filtering via `PiccoloCRUD` - you can't specify 'null' for some column types.

Take this as an example:

<img width="483" alt="Screenshot 2021-11-11 at 08 25 13" src="https://user-images.githubusercontent.com/350976/141263700-4b69098d-ad38-4de3-b3ef-f88438b595d3.png">

The user can't type in 'null'. In Piccolo Admin, a solution is to add 'null' as an option in the operator dropdown (similar to 'Equals' etc).

When PiccoloCRUD receives an operator value of 'null' it should ignore the value it receives, and treat it as null instead.

**Comment by sinisaos** [comment]
@dantownsend Did you mean something like this?
```Python
# crud/endpoints.py
from piccolo.columns.operators import (
    Equal,
    GreaterEqualThan,
    GreaterThan,
    IsNull,
    LessEqualThan,
    LessThan,
)

OPERATOR_MAP = {
    "lt": LessThan,
    "lte": LessEqualThan,
    "gt": GreaterThan,
    "gte": GreaterEqualThan,
    "e": Equal,
    "null": IsNull,
}
```
and then in Piccolo Admin

```javascript
// components/OperatorField.vue

data() {
    return {
        operators: [
            {
                label: "Less Than",
                value: "lt"
            },
            {
                label: "Less Than or Equal To",
                value: "lte"
            },
            {
                label: "Equals",
                value: "e"
            },
            {
                label: "Greater Than or Equal To",
                value: "gte"
            },
            {
                label: "Greater Than",
                value: "gt"
            },
            {
                label: "Null",
                value: "null"
            }
        ]
    }
}
```

**Comment by dantownsend** [comment]
@sinisaos Yes, that's right.

We just need to check on the front end if the field is nullable, and if so we show the 'nullable' option in the dropdown.

**Comment by sinisaos** [comment]
@dantownsend OK. I'll try to do it.
