### ISSUE TITLE
PATCH endpoint behaves differently

### ISSUE THREAD

**Issue by trondhindenes** [piccolo-orm/piccolo_api#126]
Noticing that the response from PATH seems to be a text-type instead of json-type response. I'm noticing in the code that the PATH response uses `JSONResponse` instead of the `CustomJSONResponse` used by many other endpoints. 
As far as I can see, functions either use json response with a dict input:
```
JSONResponse(self.pydantic_model.schema()
```
or `CustomJSONResponse` with a string input:
```
        json = self.pydantic_model_plural(
            include_readable=include_readable,
            include_columns=tuple(visible_columns),
            nested=nested,
        )(rows=rows).json()
        return CustomJSONResponse(json, headers=headers)
```

the PATCH response is the only one using `JSONResponse` with a string param. 

I'm guessing this is just a bug (and not a critical one at that) but before I submit a PR to fix I just wanted to make sure.

**Comment by dantownsend** [comment]
@trondhindenes Yeah, it should be `CustomJSONResponse`.

`JSONResponse` uses `json.dumps` to convert the Python dict into a JSON string, and it doesn't handle some types. Pydantic's JSON conversion covers way more types, so I tend to use this instead with `CustomJSONResponse`.

So yeah, it's a bug - well spotted.

**Comment by trondhindenes** [comment]
yup, I assumed something like that. Should be fairly easy to fix, I can take a stab at it.

**Comment by dantownsend** [comment]
@trondhindenes Great, thanks
