### ISSUE TITLE
KeyError when creating Pydantic models?

### ISSUE THREAD

**Issue by wmshort** [piccolo-orm/piccolo_api#129]
@dantownsend I've just upgraded my infrastructure to the latest version of FastAPI and I'm now getting a strange error when trying to view the Swagger UI. In the first instance FastAPI is giving me a "failed to load API definition" which is a problem with retrieving the OpenAPI JSON spec. Digging a bit more into the problem however reveals that something is going on when creating the Pydantic response models.

Fetch error
Response status is 500 /api/openapi.json

Digging a bit more into the problem however reveals that something is going on when creating the Pydantic response models. I assume this is soemthing to do with ``create_pydantic_model``. I'm getting an error like the one here, which is the closest I can find to any explanation of the issue:

https://github.com/tiangolo/fastapi/issues/1505

The relevant bit in my case is:

  File "/usr/local/lib/python3.7/site-packages/fastapi/openapi/utils.py", line 364, in get_openapi
    flat_models=flat_models, model_name_map=model_name_map
  File "/usr/local/lib/python3.7/site-packages/fastapi/utils.py", line 28, in get_model_definitions
    model_name = model_name_map[model]
KeyError: <class 'pydantic.main.Lemma'>

I'm stumped, as nothing has changed _at all_ in my model / table definitions since the update. Is this likely something due to the interaction of Piccolo  - Pydantic - FastAPI or out of Piccolo's scope?

**Comment by dantownsend** [comment]
@wmshort I know that Pydantic was recently updated, which might be the cause of the issue.

Have you tried using an explicit `model_name` with `create_pydantic_model`? I've encountered an issue before with FastAPI and Pydantic which was solved by this.

```python
create_pydantic_model(SomeTable, model_name="my_unique_model_name")
```

It's a shot in the dark, but might help.

I'll try and replicate the issue.

**Comment by wmshort** [comment]
I had the same thought, but in fact I was doing that already on the models, so it couldn't have been causing the problems. I did just see somewhere else that having an Enum of the same name on two models might cause the issue! I do have this on my models, so I'm going to try this change. Will report back.

**Comment by sinisaos** [comment]
@wmshort I can replicate your `KeyError` problem only if I do not use the explicit `model_name` with `create_pydantic_model`. If I use `model_name` everything is fine. `FastAPIWrapper` works fine. Both Python3.7 and Python3.8 with latest `FastAPI (v0.71.0)`, `Pydantic (v1.9.0)` and latest `Piccolo`. Can you show us your schema from tables so we can try it out?

**Comment by dantownsend** [comment]
@sinisaos Thanks for taking a look.

I tried updating my apps to the latest FastAPI, and it seems OK. So the bug must be quite subtle.

@wmshort The only other things I can think of at the moment are:

 * Make sure `model_name` matches the variable name. So `MyModel = create_pydantic_model(SomeTable, model_name="MyModel")`.
 * Make sure `create_pydantic_model` is called within the global scope, and not within a function or something.

**Comment by sinisaos** [comment]
@dantownsend William sent me his schema and the only thing I noticed is that in Python 3.7 (which William uses as seen from the error logs) we **MUST** use `model_name` because `post` and `put` routes are a problem (they use `SomeModelIn` and `SomeModelOut` if we write endpoints by ourselves) . In Python 3.8 we don't have to use `model_name` and everything work fine. I don't know if it will solve the William problem but I don't see anything else.

**Comment by dantownsend** [comment]
@sinisaos OK, thanks for checking. If it works for Python 3.8 and above, that's definitely helpful to know.

**Comment by wmshort** [comment]
Thanks, both. All of these conditions are true already, apart from the Python version. I'll give that a try. Otherwise it's probably some corner case and I'll have to experiment some with ``model_name``. Is there any chance it has to do with ``nested`` and some naming clash there?

**Comment by dantownsend** [comment]
@wmshort Yes, nested could be the cause.

**Comment by wmshort** [comment]
After a little more experimentation I've narrowed the problem down to two tables that both have _two_ ForeignKey fields referencing the same table. (Though in each case, the referenced table is different). It doesn't appear to be ``nested`` per se as certain nested tables that do not have the 'two FKs pointing to the same table' issue work perfectly well. So the problem actually seems to be related to the case of a table like:

class BattleOfTheBands(Table):
     band1 = ForeignKey(references=Band)
     band2 = ForeignKey(references=Band)

which does not appear to play nice with Pydantic, at least under my configuration. Strange, as I am now using Python 3.8 and latest versions of dependencies, which worked for @sinisaos. I'm stumped!
