### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_api#150]
Now that Piccolo API has a fairly broad set of features, it's important to improve upon the documentation.

I think the following needs adding:

- [x] A 'basics' page - explaining how ASGI middleware works
- [x] Make sure all of the examples are easy to understand
- [x] Improve JWT and Token Auth docs - they don't document the endpoints properly

**Comment by sinisaos** [comment]
@dantownsend You can close this issue because it's done.
