### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by sinisaos** [piccolo-orm/piccolo_api#163]
I find a small bug. After the last changes in Piccolo ORM `Table.__init__` `ignore_missing` argument is now `_ignore_missing` and we have to change [this line ](https://github.com/piccolo-orm/piccolo_api/blob/af7043b064081343c9e46eaef5750896edf15c04/piccolo_api/crud/endpoints.py#L850)  to `row = self.table(_ignore_missing=True)` otherwise we get 500 Internal Server Error from `get_new` method. If you want I can change it.

**Comment by dantownsend** [comment]
Yes - if you could create a PR that would be great, thanks!

I didn't realise we were using `ignore_missing` in Piccolo API. I try and avoid breaking changes, it's my mistake.
