### ISSUE TITLE
"Unable to split hashed password"

### ISSUE THREAD

**Issue by 56907dzq** [piccolo-orm/piccolo_api#189]
I use piccolo-admin,when change user's active key to false,the password was set to "".
When the user login again,will raise internal server error by the reason of title.
Can add something to  reduce this?

**Comment by sinisaos** [comment]
@56907dzq Yes, you're right, it's not working as it should right now. Here's a [PR](https://github.com/piccolo-orm/piccolo_api/pull/158) and this is code https://github.com/piccolo-orm/piccolo_api/blob/b643e9519be8c92a4e27c82b17d234d97a8bd6b0/piccolo_api/crud/endpoints.py#L1044-L1056
 that should fix it, but somehow it's staled.

**Comment by dantownsend** [comment]
Yeah, I'll get that fix merged in.

**Comment by dantownsend** [comment]
@56907dzq This should be fixed now in `piccolo_api==0.48.0`. Thanks for reporting this issue.

**Comment by 56907dzq** [comment]
It's my pleasure
