### ISSUE TITLE
Update `logging.getLogger()` to use `__name__` instead of `__file__`

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_api#198]
We need to do the same for the Piccolo API code base.

See this issue for more info:

https://github.com/piccolo-orm/piccolo/issues/653

**Comment by VishMaster17** [comment]
Hi @dantownsend , I'd like to take this up. Kindly assign me.

**Comment by dantownsend** [comment]
@VishMaster17 Cool, thanks - I've assigned you.

**Comment by dantownsend** [comment]
Fixed be https://github.com/piccolo-orm/piccolo_api/pull/199
