### ISSUE TITLE
Alpha version for Pydantic 2.0 / Piccolo 1.0a1?

### ISSUE THREAD

**Issue by mastercoms** [piccolo-orm/piccolo_api#253]
Would it be possible to release an alpha version to upgrade the dependencies for FastAPI and Pydantic for the new Pydantic 2.0 support found in Piccolo 1.0a1?

**Comment by dantownsend** [comment]
Yeah, I'll try and get this done this week. We've done most of the work - just needs a final test, and then to be released.

**Comment by dantownsend** [comment]
It's available now:

https://pypi.org/project/piccolo-api/1.0a1/

Just Piccolo Admin left, and then once we know they all work well together, will go proper v1.
