### ISSUE TITLE
Issue with updating and bulk updating `BaseUser` via admin panel

### ISSUE THREAD

**Issue by jrycw** [piccolo-orm/piccolo_api#273]
This issue arose while attempting to update or bulk update the Piccolo `BaseUser` via the admin panel, while following the repository [headless-forum-fastapi](https://github.com/sinisaos/headless-forum-fastapi).

Currently, the implementation of `piccolo_api/crud/endpoints.py/patch_single` works correctly when an admin user wants to change the password. However, it encounters issues when attempting to update or bulk update a Piccolo `BaseUser`.

After discussing with @sinisaos [here](https://github.com/sinisaos/headless-forum-fastapi/issues/4), we devised [a working solution](https://github.com/sinisaos/headless-forum-fastapi/issues/4#issuecomment-2000578729). 
```python
@apply_validators
@db_exception_handler
async def patch_single(
    self, request: Request, row_id: PK_TYPES, data: t.Dict[str, t.Any]
) -> Response:
    """
    Patch a single row.
    """
    cleaned_data = self._clean_data(data)

    try:
        model = self.pydantic_model_optional(**cleaned_data)
    except pydantic.ValidationError as exception:
        return Response(str(exception), status_code=400)

    cls = self.table

    try:
        values = {getattr(cls, key): getattr(model, key) for key in data.keys()}
    except AttributeError:
        unrecognised_keys = set(data.keys()) - set(model.model_dump().keys())
        return Response(
            f"Unrecognised keys - {unrecognised_keys}.",
            status_code=400,
        )

    if self._hook_map:
        values = await execute_patch_hooks(
            hooks=self._hook_map,
            hook_type=HookType.pre_patch,
            row_id=row_id,
            values=values,
            request=request,
        )
    # ==========================================
    # method 1 from @jrycw 
    if issubclass(cls, BaseUser):
        if password := values.pop("password", None):
            cls._validate_password(password)
            values["password"] = cls.hash_password(password)

    # method 2 from @sinisaos 
    if issubclass(cls, BaseUser):
        try:
            # if password is changed
            if values["password"]:
                cls._validate_password(values["password"])
                values["password"] = cls.hash_password(values["password"])
            else:
                # use previous password
                values.pop("password")
        except KeyError:
            pass
    # ==========================================
    try:
        await cls.update(values).where(cls._meta.primary_key == row_id).run()
        new_row = (
            await cls.select(exclude_secrets=self.exclude_secrets)
            .where(cls._meta.primary_key == row_id)
            .first()
            .run()
        )
        assert new_row
        return CustomJSONResponse(self.pydantic_model(**new_row).model_dump_json())
    except ValueError:
        return Response("Unable to save the resource.", status_code=500)
```

However, this solution has raised another concern: what happens when we bulk update a field that is subject to a unique constraint? It appears that while we can update the first row successfully, subsequent rows fail. We're unsure if this is the correct behavior, or if there should be logic in place to prevent bulk updates when using the admin panel.

**Comment by dantownsend** [comment]
Interesting. I haven't tried bulk updating the `BaseUser` table. I'll give it a go.

**Comment by dantownsend** [comment]
I just gave it a go, and I can see what you mean. A 500 error was being raised.

I've tried out your suggested fix, and it all seems to work great.

**Comment by dantownsend** [comment]
Do you mind creating a PR with the changes?

I'm happy with either method. Lets go with this as it's a bit shorter:

```python
    if issubclass(cls, BaseUser):
        if password := values.pop("password", None):
            cls._validate_password(password)
            values["password"] = cls.hash_password(password)
```

I noticed that we don't handle the potential exception raised by `cls._validate_password(password)`. For example, if the password is too short. It would be nice to return a 400 error.

**Comment by jrycw** [comment]
> Do you mind creating a PR with the changes?
> 
> I'm happy with either method. Lets go with this as it's a bit shorter:
> 
> ```python
>     if issubclass(cls, BaseUser):
>         if password := values.pop("password", None):
>             cls._validate_password(password)
>             values["password"] = cls.hash_password(password)
> ```
> 
> I noticed that we don't handle the potential exception raised by `cls._validate_password(password)`. For example, if the password is too short. It would be nice to return a 400 error.

@dantownsend Absolutely, I'm more than willing to submit a PR. However, if we attempt to handle the exception as follows:
```python
        if issubclass(cls, BaseUser):
            if password := values.pop("password", None):
                try:
                    cls._validate_password(password)
                except ValueError as e:
                    return Response(f"{e}", status_code=400)
                values["password"] = cls.hash_password(password)
```
it seems that `test_patch_user_fails` won't pass, as we're handling the exception and returning a response instead of raising it.
```python
    def test_patch_user_fails(self):
        ...
        with self.assertRaises(ValueError):
            response = client.patch(f"/{user['id']}/", json=json)
>           self.assertEqual(response.content, b"The password is too short.")
E           AssertionError: ValueError not raised
```

**Comment by jrycw** [comment]
> I just gave it a go, and I can see what you mean. A 500 error was being raised.
> 
> I've tried out your suggested fix, and it all seems to work great.

The fix should ensure that `patch_single` behaves correctly and addresses potential issues with updating and bulk updating (for fields not subject to unique constraints) using the admin panel.

However, when bulk updating fields subject to unique constraints (across any tables, not just `BaseUser`) via the admin panel, the first row is successfully updated, but subsequent rows fail. This behavior shouldn't be attributed to `patch_single`, as it functions correctly. One potential solution is to filter out fields subject to unique constraints in advance within the admin panel. However, it seems this issue is related to `piccolo_admin` and may require further investigation.

**Comment by sinisaos** [comment]
> However, when bulk updating fields subject to unique constraints (across any tables, not just `BaseUser`) via the admin panel, the first row is successfully updated, but subsequent rows fail. This behavior shouldn't be attributed to `patch_single`, as it functions correctly. One potential solution is to filter out fields subject to unique constraints in advance within the admin panel. However, it seems this issue is related to `piccolo_admin` and may require further investigation.

This can be solved by adding a `unique` argument to an column extra in pydantic schema like this
```Python
# in piccolo/utils/pydantic.py
extra: JsonDict = {
    "help_text": column._meta.help_text,
    "choices": column._meta.get_choices_dict(),
    "secret": column._meta.secret,
    "nullable": column._meta.null,
    "unique": column._meta.unique, # new argument
}
```
After that we can simply not show unique column in `Bulkupdate` dropdown like this
```Vue
// in BulkUpdateModal.vue
<template v-for="(property, columnName) in schema.properties">
    <option
        :key="columnName"
        :value="columnName"
        v-if="
            columnName != schema.extra.primary_key_name &&
            property.extra.unique == false // check if column is unique
        "
    >
        {{ property.title }}
    </option>
</template>
```
This will disable the attempt to update in bulk unique columns. Any thoughts?

**Comment by jrycw** [comment]
> > However, when bulk updating fields subject to unique constraints (across any tables, not just `BaseUser`) via the admin panel, the first row is successfully updated, but subsequent rows fail. This behavior shouldn't be attributed to `patch_single`, as it functions correctly. One potential solution is to filter out fields subject to unique constraints in advance within the admin panel. However, it seems this issue is related to `piccolo_admin` and may require further investigation.
> 
> This can be solved by adding a `unique` argument to an column extra in pydantic schema like this
> 
> ```python
> # in piccolo/utils/pydantic.py
> extra: JsonDict = {
>     "help_text": column._meta.help_text,
>     "choices": column._meta.get_choices_dict(),
>     "secret": column._meta.secret,
>     "nullable": column._meta.null,
>     "unique": column._meta.unique, # new argument
> }
> ```
> 
> After that we can simply not show unique column in `Bulkupdate` dropdown like this
> 
> ```
> // in BulkUpdateModal.vue
> <template v-for="(property, columnName) in schema.properties">
>     <option
>         :key="columnName"
>         :value="columnName"
>         v-if="
>             columnName != schema.extra.primary_key_name &&
>             property.extra.unique == false // check if column is unique
>         "
>     >
>         {{ property.title }}
>     </option>
> </template>
> ```
> 
> This will disable the attempt to update in bulk unique columns. Any thoughts?

@sinisaos I consider this approach to be beneficial because by filtering the fields subjected to unique constraints in advance while bulk updating, we can offer the best user experience for those using the admin panel. If other users are dissatisfied with this approach, they still have the option to build the interface they desire using `piccolo_api` directly.

**Comment by sinisaos** [comment]
@jrycw I also think it's an easy way (hiding the unique column field) to prevent admin errors. Bulk updating unique columns doesn't make sense because it breaks unique constraints (we have that case now because we can only update the first row, but already the next row raise error because unique constraints are violated), but we'll have to wait and see what Daniel says about all this.

**Comment by dantownsend** [comment]
@jrycw Yes, that looks good to me - thanks!

**Comment by sinisaos** [comment]
@dantownsend If you want, I can do a unique column PR for Piccolo and Piccolo Admin in the evening?

**Comment by dantownsend** [comment]
@sinisaos That would be good, thanks!

**Comment by sinisaos** [comment]
@jrycw Can you please close this issue as all bugs from this issue are now resolved. Thanks.

**Comment by jrycw** [comment]
@sinisaos Sure, thank you once again for your assistance!
