### ISSUE TITLE
`401` vs `403` in JWTAuth

### ISSUE THREAD

**Issue by sinisaos** [piccolo-orm/piccolo_api#301]
I think we should change the `status_code` from `403` to `401` if [credentials are missing or incorrect](https://supertokens.com/blog/http-error-codes-401-vs-403). In [TokenAuth](https://github.com/piccolo-orm/piccolo_api/blob/d6ed009d36d0f965aee3597cde956dd5dc4491e6/piccolo_api/token_auth/endpoints.py#L55-L69) and [SessionAuth](https://github.com/piccolo-orm/piccolo_api/blob/d6ed009d36d0f965aee3597cde956dd5dc4491e6/piccolo_api/session_auth/endpoints.py#L95) we use the proper `401` `status_code`. Sorry if  I'm wrong.

**Comment by dantownsend** [comment]
Oh, I see what you're saying - in this bit:

https://github.com/piccolo-orm/piccolo_api/blob/d6ed009d36d0f965aee3597cde956dd5dc4491e6/piccolo_api/jwt_auth/middleware.py#L135-L157

Having read that article, I think you're right and they should be 401.

Feel free to change them. I assume a couple of tests will need updating too.

**Comment by sinisaos** [comment]
@dantownsend  I made [PR](https://github.com/piccolo-orm/piccolo_api/pull/302)
