### ISSUE TITLE
Increase code coverage

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_api#63]
Now we have codecov integrated, it's easier to track code coverage.

There are some areas of the code base which require additional testing.

**Comment by aminalaee** [comment]
@dantownsend Can this be closed?

**Comment by dantownsend** [comment]
@aminalaee Yes, I can close it.

Looking at the coverage now, it's much better - thanks for that.

Only minor bits of coverage are missing now, and I can create separate issues for those.
