### ISSUE TITLE
Support nested model created with `create_pydantic_model`

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_api#76]
As suggested here:

https://github.com/piccolo-orm/piccolo/issues/202

It would be great if `create_pydantic_model` could generate nested models.

```python
create_pydantic_model(Band, nested_models=[Band.manager])
```

This would output something equivalent to this:

```python
from pydantic import BaseModel

class ManagerModel:
    name: str    

class BandModel:
    name: str
    manager: ManagerModel

```

**Comment by aminalaee** [comment]
@dantownsend This is cool, I just have a question, should `create_pydantic_model` now return a list of models? In case of nested models returning two?

**Comment by dantownsend** [comment]
@aminalaee Yeah, it's a good point. I think it would just return a single model still. The child models would just be created internally by `create_pydantic_model`.

It's a bit ugly, but you could still access the sub models if you wanted them.

```python
class Manager(Table):
    name = Varchar()

class Band(Table):
    name = Varchar()
    manager = ForeignKey(Manager)

BandModel = create_pydantic_model(Band, nested=True)
BandModel.__fields__['manager'].type_
>>> ManagerModel
```

What do you think?

**Comment by aminalaee** [comment]
@dantownsend  I have to  say I like `BandModel = create_pydantic_model(Band, nested=True)` better than previous ones.
Let me try it out.

**Comment by dantownsend** [comment]
@aminalaee Great, thanks
