### ISSUE TITLE
Overhaul Pydantic docs

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_api#79]
Piccolo API has great Pydantic support, but the docs are a bit hidden away under the 'CRUD' section.

It would be good to move them, so 'Serialisation' is a top level topic in the docs, and contains much more examples about how to use `create_pydantic_model`.

**Comment by sinisaos** [comment]
@dantownsend I'll make PR for Piccolo and Piccolo API to change docs.

**Comment by sinisaos** [comment]
@dantownsend Can you please close this issue because it is done in main `Piccolo ORM` repo.

**Comment by dantownsend** [comment]
@sinisaos Yep - good point
