### ISSUE TITLE
Make `exclude_columns` work with `nested` for `create_pydantic_model`

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_api#80]
We have two great new features for `create_pydantic_model` (`exclude_columns` and `nested`).

I'd like to make sure that they work together. For example:

```python
create_pydantic_model(Band, nested=True, exclude_columns=(Band.manager.id,))
```

In which case the `Manager` sub model would omit it's `id` column.

**Comment by dantownsend** [comment]
@sinisaos Yeah, it's unfortunate. Not an urgent issue, but would be nice to have.

**Comment by sinisaos** [comment]
@dantownsend Can you please close this issue because it's done with latest changes.

**Comment by dantownsend** [comment]
@sinisaos Yep, good point. Fixed by https://github.com/piccolo-orm/piccolo_api/pull/98
