### ISSUE TITLE
Add a complete session auth example to the docs

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_api#83]
It would be useful to show an app which has all of the session auth components working together (`session_login`, `session_logout` and `SessionsAuthBackend`).

Here's an example:

```python
import datetime
from fastapi import FastAPI
from piccolo_api.csrf.middleware import CSRFMiddleware
from piccolo_api.openapi.endpoints import swagger_ui
from piccolo_api.session_auth.endpoints import session_login, session_logout
from piccolo_api.session_auth.middleware import SessionsAuthBackend
from starlette.middleware import Middleware
from starlette.middleware.authentication import AuthenticationMiddleware
from starlette.routing import Route

app = FastAPI()

app.mount(
    "/login/",
    session_login(),
)

private_app = FastAPI(
    routes=[
        Route("/logout/", session_logout()),
    ],
    middleware=[
        Middleware(
            AuthenticationMiddleware,
            backend=SessionsAuthBackend(
                increase_expiry=datetime.timedelta(minutes=30)
            ),
        ),
        Middleware(CSRFMiddleware, allow_form_param=True),
    ],
    docs_url=None,
    redoc_url=None,
)

# The Swagger docs which come with FastAPI don't support CSRF middleware, so we mount
# a custom one which Piccolo provides (accessible at /private/docs):
private_app.mount("/docs/", swagger_ui(schema_url="/private/openapi.json"))

@private_app.get('/my-secret-endpoint/')
def my_endpoint():
    # This is just a normal FastAPI endpoint, and is protected by Session Auth
    pass

app.mount("/private/", private_app)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app)
```

**Comment by sinisaos** [comment]
@dantownsend Do you think of the whole app as in the [Piccolo examples](https://github.com/piccolo-orm/piccolo_examples)? If not your example from comment is perfect example of `SessionAuth` and that should be in docs.

**Comment by dantownsend** [comment]
@sinisaos The example code here might be sufficient.

I was thinking of a new page in the docs, with this code in it.

<img width="570" alt="Screenshot 2021-09-07 at 13 59 21" src="https://user-images.githubusercontent.com/350976/132348953-27ae6940-9db2-485e-8ad3-d3ef4ccebe8c.png">

The example code is an abbreviated form of one of my own apps - I haven't actually tested it standalone, but it looks correct.

What I'd love is if we had a new folder in the repo called `examples`. This file would be in there, and we'd somehow embed it within the docs.

I know Sphinx can be used to embed fragments of files, but I haven't tried embedding an entire file before.

**Comment by sinisaos** [comment]
@dantownsend I have a question. I don't know anything about Sphinx's embed fragments of files, but I created a Piccolo Task starter app (based on your example) with `SessionAuth` where openapi docs are private and the home page is public. Everything works great, but I don’t know if I need to push the app to my Github repo and then you can put a link in the Piccolo examples or what to do with it? Thanks in advance.

**Comment by dantownsend** [comment]
@sinisaos I think it would be nice to embed the code directly in the docs.

I've figured out how to embed entire Python files:

```rst
Full example
============

.. include:: example.py
    :code: python
```

**Comment by dantownsend** [comment]
If you wanted to push your code to a new repo, I don't mind linking to it from the ``piccolo_examples`` repo.

But I'd still like to embed an example in the Piccolo API docs.

**Comment by dantownsend** [comment]
Thanks for checking the example code works.

**Comment by sinisaos** [comment]
@dantownsend I made `examples` folder in SessionAuth directory in docs and then embed with
```rst
Full example
============

.. include:: ./examples/example.py
    :code: python
```
Result is:

![example](https://user-images.githubusercontent.com/30960668/132380349-56a8b44f-6fa0-4f91-9846-deb18a2a93d0.png)

Did you mean something like this or?

**Comment by dantownsend** [comment]
@sinisaos That's right - but can we put the example in it's own page?

**Comment by sinisaos** [comment]
@dantownsend Yes we can.
Index page

![index](https://user-images.githubusercontent.com/30960668/132384454-551a86ca-a0c9-48c4-a0a5-7414b913625b.png)

Full example page

![example](https://user-images.githubusercontent.com/30960668/132384522-4de25e48-9623-4012-9989-8608e74a6ef1.png)

**Comment by dantownsend** [comment]
@sinisaos That's great, thanks

**Comment by dantownsend** [comment]
If you open it as PR, I'll get it merged.

**Comment by sinisaos** [comment]
@dantownsend I'll do it in a few minutes.

**Comment by wmshort** [comment]
Excellent

**Comment by dantownsend** [comment]
Fixed by https://github.com/piccolo-orm/piccolo_api/pull/86
