### ISSUE TITLE
SessionsAuthBackend.authenticate honor allow_unauthenticated if not token

### ISSUE THREAD

**Issue by Bakz** [piccolo-orm/piccolo_api#89]
Hello, sorry if this is a naive assertion, but shouldn't SessionsAuthBackend.authenticate return (AuthCredentials(scopes=[]), UnauthenticatedUser()) if not token but self.allow_unauthenticated == True?

**Comment by dantownsend** [comment]
@Bakz you're correct - if `allow_unauthenticated` is `True`, and the middleware can't find a session for that user, it should return `(AuthCredentials(scopes=[]), UnauthenticatedUser())`.

See here:

https://github.com/piccolo-orm/piccolo_api/blob/6273f7b72204f7514d3ac566cd7980b25405c81d/piccolo_api/session_auth/middleware.py#L94

Does that help?

**Comment by dantownsend** [comment]
Ah, I see you point now. It's here:

https://github.com/piccolo-orm/piccolo_api/blob/6273f7b72204f7514d3ac566cd7980b25405c81d/piccolo_api/session_auth/middleware.py#L75

You're correct - this looks like a bug, where it will deny them if they don't have a cookie.

**Comment by dantownsend** [comment]
@Bakz I've released the fix - it's v0.25.1 on PyPI.

If it fixes your issue, I'll close this. Thanks.

**Comment by Bakz** [comment]
@dantownsend saw that you also added the if not user_id case - all looks good now. Btw heard about you and your work on Talk Python. I'm loving piccolo - thank you for all your hard work!

**Comment by dantownsend** [comment]
@Bakz Thanks for the kind words. If you find any other issues, or have any suggestions for improvements let me know!

**Comment by dantownsend** [comment]
Fixed by https://github.com/piccolo-orm/piccolo_api/pull/90
