### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_api#93]
Now that Python 3.10 has been released, we need to check if Piccolo API works with it, and update the GitHub actions accordingly.

This PR from the main Piccolo repo is a good example of what's required:

https://github.com/piccolo-orm/piccolo/pull/304

**Comment by sinisaos** [comment]
@dantownsend Can you please close this issue because it is done.

**Comment by dantownsend** [comment]
Done
