### ISSUE TITLE
Be able to request a subset of columns from PiccoloCRUD's GET endpoint

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_api#97]
For example:

```
/api/tables/movie?__fields=id,name
```

Would return:

```json
{
    "rows": [
        {
            "id": 17,
            "name": "The Hobbit: The Battle of the Five Armies",
        },
     ]
}
```

This is generally useful, but would be great for Piccolo Admin too, as when a user uses a ``TableConfig`` to specify that the list page should only show a subset of columns, we aren't over fetching data.

**Comment by dantownsend** [comment]
@wmshort This feature is pretty much done now, except I'm not sure on the naming of the parameter.

What do you think is most suitable? `__fields`, `__columns`, `__visible_fields`?

**Comment by wmshort** [comment]
Personally I find 'fields' the most intuitive but any of these will be clear enough. Glad this has come together. Nice!

**Comment by dantownsend** [comment]
@wmshort Thanks - naming stuff is hard! It's good to have a sanity check.

**Comment by sinisaos** [comment]
@dantownsend Can you please close this issue because it's done with latest changes.

**Comment by dantownsend** [comment]
Fixed by https://github.com/piccolo-orm/piccolo_api/pull/98
